const ObjectHuman = [

  {
    name: "Bablu Sarkar",
    role: "Student",
    imagePath: "/images/bablu.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000742",
    projectRole: "Team Leader",
    batch: "2022-2026",
  },
  {
    name: "Chandra Bhushan Kumar",
    role: "Student",
    imagePath: "/images/bhushan.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000745",
    projectRole: "UI Developer",
    batch: "2022-2026",
  },

  {
    name: "Gyanendra",
    role: "Student",
    imagePath: "/images/gyanendra.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000744",
    projectRole: "Idea & Design Developer",
    batch: "2022-2026",
  },
  
  {
    name: "Amarjeet Kumar",
    role: "Student",
    imagePath: "/images/amarjeet.jpg",
    department: "IT",
    college: "SITE",
    enrollment_No: "2201000000743",
    projectRole: "Team Supporter ",
    batch: "2022-2026",
  },
  
  
  {
    name: "Dr. Ashima",
    role: "Faculty",
    imagePath: "/images/ashima.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000746",
    projectRole: "Mentor",
  },
  {
    name: "Dr. Sharvan",
    role: "Faculty",
    imagePath: "/images/Sharvan.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000746",
  },
  {
    name: "Dr. Ravi Agarwal",
    role: "Faculty",
    imagePath: "/images/Ravi.jpg",
    department: "EEE",
    college: "SITE",
    enrollment_No: "SU201500100",
  },
  {
    name: "Dr.Tarun Kumar",
    role: "Faculty",
    imagePath: "/images/Tarun.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "SU201500100",
  },
  {
    name: "Ankita Kumari",
    role: "Student",
    imagePath: "/images/Ankita.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "20106000035837",
    projectRole: "no",
    batch: "2022-2026",
  },
  {
    name: "Navneet Kumar",
    role: "Student",
    imagePath: "/images/Navneet.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "20106000035837",
    projectRole: "no",
    batch: "2022-2026",
  },
  {
    name: "Abhishek Kumar",
    role: "Student",
    imagePath: "/images/Abhishek.jpg",
    department: "CSE",
    college: "BJSEC",
    enrollment_No: "22106000002016",
    projectRole: "no",
    batch: "2022-2026",
  },
  {
    name: "Sumit Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000258",
    projectRole: "no",
    batch: "2022-2026",
  },
  {
    name: "Sumit Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000258",
    projectRole: "no",
    batch: "2022-2026",
  },
];
export default ObjectHuman;
