const ObjectHuman = [
  {
    name: "Bablu kumar",
    role: "Student",
    imagePath: "/images/bablu.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000742",
    projectRole: "Team Leader",
    batch: "2022-2026",
  },
  {
    name: "Chandra Bhushan Kumar",
    role: "Student",
    imagePath: "/images/bhushan.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000745",
    projectRole: "UI Developer",
    batch: "2022-2026",
  },

  {
    name: "Gyanendra Chaughary ",
    role: "Student",
    imagePath: "/images/gyanendra.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "22106000001231",
    projectRole: "Idea & Design Developer",
    batch: "2022-2026",
  },

  {
    name: "Amarjeet Kumar",
    role: "Student",
    imagePath: "/images/amarjeet.jpg",
    department: "IT",
    college: "SITE",
    enrollment_No: "2201000000743",
    projectRole: "Team Supporter ",
    batch: "2022-2026",
  },

  {
    name: "Dr. Ashima",
    role: "Faculty",
    imagePath: "/images/ashima.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000746",
    projectRole: "Mentor",
  },
  {
    name: "Dr. Sharvan",
    role: "Faculty",
    imagePath: "/images/Sharvan.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000746",
  },

  {
    name: "Dr. Ravi Agarwal",
    role: "Faculty",
    imagePath: "/images/Ravi.jpg",
    department: "EEE",
    college: "SITE",
    enrollment_No: "SU201500100",
  },
  {
    name: "Dr.Tarun Kumar",
    role: "Faculty",
    imagePath: "/images/Tarun.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "SU201500100",
  },

  {
    name: "Ankita Kumari",
    role: "Student",
    imagePath: "/images/Ankita.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "20106000035837",
    projectRole: "no",
    batch: "2022-2026",
  },
  {
    name: "Shivashish Kumar",
    role: "Student",
    imagePath: "/images/shivashish.jpg",
    department: "Ag.",
    college: "KVSCOS",
    enrollment_No: "2206000002916",
    projectRole: "no",
    batch: "2022-2026",
  },

  {
    name: "Navneet Kumar",
    role: "Student",
    imagePath: "/images/Navneet.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "20106000035837",
    projectRole: "no",
    batch: "2022-2026",
  },
  {
    name: "Abhishek Kumar",
    role: "Student",
    imagePath: "/images/Abhishek.jpg",
    department: "CSE",
    college: "BJSEC",
    enrollment_No: "22106000002016",
    projectRole: "no",
    batch: "2022-2026",
  },
  {
    name: "Sumit Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000258",
    projectRole: "no",
    batch: "2022-2026",
  },

  //  this data is rend......

  {
    name: "Rahul Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000001",
    batch: "2022-2026",
  },
  {
    name: "Priya Sharma",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000002",
    batch: "2022-2026",
  },
  {
    name: "Ankit Yadav",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000003",

    batch: "2022-2026",
  },
  {
    name: "Sneha Singh",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000004",

    batch: "2022-2026",
  },
  {
    name: "Vikas Gupta",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000005",

    batch: "2022-2026",
  },
  {
    name: "Aditi Mehta",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000006",

    batch: "2022-2026",
  },
  {
    name: "Manoj Patel",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000007",

    batch: "2022-2026",
  },
  {
    name: "Pooja Tiwari",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000008",

    batch: "2022-2026",
  },
  {
    name: "Ravi Verma",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000009",

    batch: "2022-2026",
  },
  {
    name: "Komal Joshi",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000010",

    batch: "2022-2026",
  },
  {
    name: "Ashok Reddy",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000011",

    batch: "2022-2026",
  },
  {
    name: "Neha Rani",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000012",

    batch: "2022-2026",
  },
  {
    name: "Karan Rawat",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000013",

    batch: "2022-2026",
  },
  {
    name: "Sonal Agarwal",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000014",

    batch: "2022-2026",
  },
  {
    name: "Shivani Sharma",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000015",

    batch: "2022-2026",
  },
  {
    name: "Nikhil Verma",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000016",

    batch: "2022-2026",
  },
  {
    name: "Sandeep Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000017",

    batch: "2022-2026",
  },
  {
    name: "Tanuja Mishra",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000018",

    batch: "2022-2026",
  },
  {
    name: "Jitendra Singh",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000019",

    batch: "2022-2026",
  },
  {
    name: "Meenal Patel",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000020",

    batch: "2022-2026",
  },
  {
    name: "Ankush Yadav",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000021",

    batch: "2022-2026",
  },
  {
    name: "Simran Kaur",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000022",

    batch: "2022-2026",
  },
  {
    name: "Rajeev Gupta",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000023",

    batch: "2022-2026",
  },
  {
    name: "Shubham Jha",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000024",

    batch: "2022-2026",
  },
  {
    name: "Ayesha Kapoor",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000025",

    batch: "2022-2026",
  },
  {
    name: "Nandini Rathi",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000026",

    batch: "2022-2026",
  },
  {
    name: "Praveen Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000027",

    batch: "2022-2026",
  },
  {
    name: "Rohit Choudhary",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000028",

    batch: "2022-2026",
  },
  {
    name: "Maya Singh",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000029",

    batch: "2022-2026",
  },
  {
    name: "Vishal Agarwal",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000030",

    batch: "2022-2026",
  },
  {
    name: "Arti Mishra",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000031",

    batch: "2022-2026",
  },
  {
    name: "Sahil Tiwari",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000032",

    batch: "2022-2026",
  },
  {
    name: "Priyanka Kaur",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000033",

    batch: "2022-2026",
  },
  {
    name: "Akash Gupta",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000034",

    batch: "2022-2026",
  },
  {
    name: "Laxmi Patel",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000035",

    batch: "2022-2026",
  },
  {
    name: "Nitin Bansal",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000036",

    batch: "2022-2026",
  },
  {
    name: "Vandana Soni",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000037",

    batch: "2022-2026",
  },
  {
    name: "Mohit Sharma",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000038",

    batch: "2022-2026",
  },
  {
    name: "Dinesh Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000039",

    batch: "2022-2026",
  },
  {
    name: "Ruchika Mehra",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000040",

    batch: "2022-2026",
  },
  {
    name: "Vineet Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000041",

    batch: "2022-2026",
  },
  {
    name: "Pallavi Gupta",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000042",

    batch: "2022-2026",
  },
  {
    name: "Bikram Yadav",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000043",

    batch: "2022-2026",
  },
  {
    name: "Neelam Rani",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000044",

    batch: "2022-2026",
  },
  {
    name: "Sanjay Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000045",

    batch: "2022-2026",
  },
  {
    name: "Sakshi Dubey",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000046",

    batch: "2022-2026",
  },
  {
    name: "Alok Yadav",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000047",

    batch: "2022-2026",
  },
  {
    name: "Shivendra Gupta",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000048",

    batch: "2022-2026",
  },
  {
    name: "Alisha Arora",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000049",

    batch: "2022-2026",
  },
  {
    name: "Mukul Yadav",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000050",

    batch: "2022-2026",
  },
  {
    name: "Neha Kumari",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000051",

    batch: "2022-2026",
  },
  {
    name: "Mohit Rathi",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000052",

    batch: "2022-2026",
  },
  {
    name: "Lalita Kumari",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000053",

    batch: "2022-2026",
  },
  {
    name: "Nikita Soni",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000054",

    batch: "2022-2026",
  },
  {
    name: "Kiran Verma",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000055",

    batch: "2022-2026",
  },
  {
    name: "Divya Bansal",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000056",

    batch: "2022-2026",
  },
  {
    name: "Gaurav Mehta",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000057",

    batch: "2022-2026",
  },
  {
    name: "Ajay Kumar",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000058",

    batch: "2022-2026",
  },
  {
    name: "Ravi Joshi",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000059",

    batch: "2022-2026",
  },
  {
    name: "Suman Patel",
    role: "Student",
    imagePath: "/images/Sumit.jpg",
    department: "CSE",
    college: "SITE",
    enrollment_No: "2201000000060",

    batch: "2022-2026",
  },
];
export default ObjectHuman;
